global:
  scrape_interval: 15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'truholdem-monitor'


rule_files:
  - /etc/prometheus/alerts.yml








scrape_configs:
  
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  
  - job_name: 'truholdem-backend'
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: ['backend:8080']
    scrape_interval: 10s

  
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
    scrape_interval: 10s

  
  - job_name: 'otel-metrics'
    static_configs:
      - targets: ['otel-collector:8889']
    scrape_interval: 10s

  
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']
    scrape_interval: 15s

  
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 15s
